// database/seeders/26_tramites_prueba_seeder.ts
import { BaseSeeder } from '@adonisjs/lucid/seeders'
import db from '@adonisjs/lucid/services/db'
import { DateTime } from 'luxon'

import Tramite from '#models/tramite'
import FormularioRunt from '#models/formulario_runt'
import Usuario from '#models/usuario'
import Servicio from '#models/servicio'

const SEDE_ID = 1
const HOY = DateTime.local().setZone('America/Bogota').startOf('day')

// ── Datos de prueba: 18 trámites, uno por cada tipo ─────────────────────────
const DATOS = [
  {
    tipo: 'MATRICULA_REGISTRO' as const,
    cliente: 'Carlos Alberto Ramos Pérez',
    cedula: '79456123',
    telefono: '3102345678',
    email: 'carlos.ramos@gmail.com',
    runt: {
      placa: 'BRD105',
      marca: 'Chevrolet',
      linea: 'Spark GT',
      modelo: '2022',
      color: 'Rojo',
      claseVehiculo: 'automovil',
      combustible: 'gasolina',
      noMotor: 'B12SE4567891',
      noChasis: 'KLATF196EB7254101',
      noSerie: 'KLATF196EB7254101',
      noVin: 'KLATF196EB7254101',
      tipoServicio: 'particular',
      carroceriaCodigo: 'C01',
      carroceriaTipo: 'SEDAN',
      capacidadKg: '450',
      blindaje: false,
      potenciaHp: '70',
      cilindrada: '1000',
      propPrimerApellido: 'Ramos',
      propSegundoApellido: 'Pérez',
      propNombres: 'Carlos Alberto',
      propTipoDocumento: 'cc',
      propNoDocumento: '79456123',
      propDireccion: 'Calle 45 # 3-22 Barrio Ambala',
      propCiudad: 'Ibagué',
      propTelefono: '3102345678',
      importacionTipo: 'dec_importacion',
      importacionNoDocumento: 'IMP-2022-001234',
      importacionFecha: '2022-03-15',
      alertaHurto: false,
      alertaLimPropiedad: false,
      alertaEmbargo: false,
      observaciones: 'Matrícula inicial vehículo nuevo de concesionario',
    },
  },
  {
    tipo: 'TRASPASO' as const,
    cliente: 'María Fernanda López Torres',
    cedula: '1020304050',
    telefono: '3154567890',
    email: 'mlopez@yahoo.com',
    runt: {
      placa: 'TBM234',
      marca: 'Renault',
      linea: 'Logan Expression',
      modelo: '2019',
      color: 'Blanco',
      claseVehiculo: 'automovil',
      combustible: 'gasolina',
      noMotor: 'K7MF701234A',
      noChasis: 'VF1KSDJ0001234567',
      noSerie: 'VF1KSDJ0001234567',
      noVin: 'VF1KSDJ0001234567',
      tipoServicio: 'particular',
      carroceriaCodigo: 'C01',
      carroceriaTipo: 'SEDAN',
      capacidadKg: '480',
      blindaje: false,
      potenciaHp: '82',
      cilindrada: '1400',
      propPrimerApellido: 'Gutiérrez',
      propSegundoApellido: 'Molina',
      propNombres: 'Jorge Andrés',
      propTipoDocumento: 'cc',
      propNoDocumento: '11223344',
      propDireccion: 'Carrera 5 # 22-18 Chapetón',
      propCiudad: 'Ibagué',
      propTelefono: '3112233445',
      compPrimerApellido: 'López',
      compSegundoApellido: 'Torres',
      compNombres: 'María Fernanda',
      compTipoDocumento: 'cc',
      compNoDocumento: '1020304050',
      compDireccion: 'Calle 23 # 6-45 La Pola',
      compCiudad: 'Ibagué',
      compTelefono: '3154567890',
      alertaHurto: false,
      alertaLimPropiedad: false,
      alertaEmbargo: false,
      observaciones: 'Traspaso por venta directa entre particulares',
    },
  },
  {
    tipo: 'TRASLADO_MATRICULA_REGISTRO' as const,
    cliente: 'Hernán Darío Ospina Ríos',
    cedula: '7654321',
    telefono: '3203456789',
    email: null,
    runt: {
      placa: 'HNJ987',
      marca: 'Toyota',
      linea: 'Hilux SRV',
      modelo: '2020',
      color: 'Gris Plata',
      claseVehiculo: 'camioneta',
      combustible: 'diesel',
      noMotor: '2KD7654321A',
      noChasis: 'MR0FR29G700987654',
      noSerie: 'MR0FR29G700987654', noVin: 'MR0FR29G700987654',
      tipoServicio: 'particular',
      carroceriaCodigo: 'P04',
      carroceriaTipo: 'PICKUP',
      capacidadKg: '1000', blindaje: false, potenciaHp: '144', cilindrada: '2494',
      propPrimerApellido: 'Ospina',   propSegundoApellido: 'Ríos',
      propNombres: 'Hernán Darío',    propTipoDocumento: 'cc',
      propNoDocumento: '7654321',     propDireccion: 'Carrera 13 # 45-60 El Jordán',
      propCiudad: 'Ibagué',           propTelefono: '3203456789',
      alertaHurto: false, alertaLimPropiedad: false, alertaEmbargo: false,
      observaciones: 'Traslado de Armenia a Ibagué por cambio de residencia',
    },
  },
  {
    tipo: 'RADICADO_MATRICULA_REGISTRO' as const,
    cliente: 'Sandra Patricia Nieto Mora',
    cedula: '52890012',
    telefono: '3012345678',
    email: 'sandranm@hotmail.com',
    runt: {
      placa: 'SPC456', marca: 'Chevrolet', linea: 'Aveo Family', modelo: '2017',
      color: 'Azul Oscuro', claseVehiculo: 'automovil', combustible: 'gasolina',
      noMotor: 'F16D3890012B',   noChasis: 'KLATF236V7B123456',
      noSerie: 'KLATF236V7B123456', noVin: 'KLATF236V7B123456',
      tipoServicio: 'particular', carroceriaCodigo: 'C01', carroceriaTipo: 'SEDAN',
      capacidadKg: '460', blindaje: false, potenciaHp: '85', cilindrada: '1600',
      propPrimerApellido: 'Nieto',   propSegundoApellido: 'Mora',
      propNombres: 'Sandra Patricia', propTipoDocumento: 'cc',
      propNoDocumento: '52890012',    propDireccion: 'Calle 60 # 8-15 Calambeo',
      propCiudad: 'Ibagué',           propTelefono: '3012345678',
      alertaHurto: false, alertaLimPropiedad: false, alertaEmbargo: false,
      observaciones: 'Radicado pendiente resolución de trámite anterior',
    },
  },
  {
    tipo: 'CAMBIO_COLOR' as const,
    cliente: 'Juan Esteban Vargas Salcedo',
    cedula: '1010223344',
    telefono: '3178901234',
    email: 'jvargas@gmail.com',
    runt: {
      placa: 'KLM321', marca: 'Mazda', linea: 'Mazda 3 Touring', modelo: '2021',
      color: 'Negro (antes: Gris)', claseVehiculo: 'automovil', combustible: 'gasolina',
      noMotor: 'PE061234567C',    noChasis: 'JM1BM1H71P0321456',
      noSerie: 'JM1BM1H71P0321456', noVin: 'JM1BM1H71P0321456',
      tipoServicio: 'particular', carroceriaCodigo: 'C01', carroceriaTipo: 'SEDAN',
      capacidadKg: '460', blindaje: false, potenciaHp: '155', cilindrada: '2000',
      propPrimerApellido: 'Vargas',    propSegundoApellido: 'Salcedo',
      propNombres: 'Juan Esteban',     propTipoDocumento: 'cc',
      propNoDocumento: '1010223344',   propDireccion: 'Cra 3 # 12-78 Centro',
      propCiudad: 'Ibagué',            propTelefono: '3178901234',
      alertaHurto: false, alertaLimPropiedad: false, alertaEmbargo: false,
      observaciones: 'Cambio de color por reparación de carrocería total',
    },
  },
  {
    tipo: 'CAMBIO_SERVICIO' as const,
    cliente: 'Transportes Rápidos del Tolima SAS',
    cedula: '900123456',
    telefono: '2612345678',
    email: 'admin@transrapidostolima.com',
    runt: {
      placa: 'OPQ654', marca: 'Mercedes-Benz', linea: 'Sprinter 515 CDI', modelo: '2018',
      color: 'Blanco', claseVehiculo: 'buseta', combustible: 'diesel',
      noMotor: 'OM651654321A',   noChasis: 'WDB9066352P654321',
      noSerie: 'WDB9066352P654321', noVin: 'WDB9066352P654321',
      tipoServicio: 'publico', carroceriaCodigo: 'B02', carroceriaTipo: 'BUSETA',
      capacidadKg: '3500', blindaje: false, potenciaHp: '150', cilindrada: '2143',
      propPrimerApellido: 'Rápidos',  propSegundoApellido: 'Tolima',
      propNombres: 'Transportes',     propTipoDocumento: 'nit',
      propNoDocumento: '900123456-1', propDireccion: 'Calle 17 # 2-30 La Pola',
      propCiudad: 'Ibagué',           propTelefono: '2612345678',
      alertaHurto: false, alertaLimPropiedad: false, alertaEmbargo: false,
      observaciones: 'Cambio de servicio particular a público colectivo',
    },
  },
  {
    tipo: 'REGRABAR_MOTOR' as const,
    cliente: 'Andrés Felipe Castillo Bermúdez',
    cedula: '93478901',
    telefono: '3144567890',
    email: null,
    runt: {
      placa: 'RST789', marca: 'Nissan', linea: 'Frontier 4x4', modelo: '2016',
      color: 'Azul Metalizado', claseVehiculo: 'camioneta', combustible: 'diesel',
      noMotor: 'YD25789012D',   noChasis: 'JN1TCND22Z0789012',
      noSerie: 'JN1TCND22Z0789012', noVin: 'JN1TCND22Z0789012',
      tipoServicio: 'particular', carroceriaCodigo: 'P04', carroceriaTipo: 'PICKUP',
      capacidadKg: '1200', blindaje: false, potenciaHp: '126', cilindrada: '2488',
      propPrimerApellido: 'Castillo',  propSegundoApellido: 'Bermúdez',
      propNombres: 'Andrés Felipe',    propTipoDocumento: 'cc',
      propNoDocumento: '93478901',     propDireccion: 'Cll 50 # 5B-23 Piedrapintada',
      propCiudad: 'Ibagué',            propTelefono: '3144567890',
      alertaHurto: true, alertaLimPropiedad: false, alertaEmbargo: false,
      alertaOtro: 'Motor regrabado por siniestro — acto policial 12345',
      observaciones: 'Regrabación por siniestro total. Motor reemplazado.',
    },
  },
  {
    tipo: 'REGRABAR_CHASIS' as const,
    cliente: 'Lucía Mercedes Prada Quintero',
    cedula: '41789023',
    telefono: '3123456789',
    email: 'lprada@hotmail.com',
    runt: {
      placa: 'UVW147', marca: 'Ford', linea: 'Ranger XLT', modelo: '2015',
      color: 'Plata', claseVehiculo: 'camioneta', combustible: 'diesel',
      noMotor: 'DURATORQ147258A',  noChasis: '1FTNF21L55EC147258',
      noSerie: '1FTNF21L55EC147258', noVin: '1FTNF21L55EC147258',
      tipoServicio: 'particular', carroceriaCodigo: 'P04', carroceriaTipo: 'PICKUP',
      capacidadKg: '1000', blindaje: false, potenciaHp: '143', cilindrada: '3000',
      propPrimerApellido: 'Prada',     propSegundoApellido: 'Quintero',
      propNombres: 'Lucía Mercedes',   propTipoDocumento: 'cc',
      propNoDocumento: '41789023',     propDireccion: 'Cra 6 # 34-12 Belén',
      propCiudad: 'Ibagué',            propTelefono: '3123456789',
      alertaHurto: false, alertaLimPropiedad: false, alertaEmbargo: false,
      observaciones: 'Chasis dañado en accidente. Regrabación autorizada por perito.',
    },
  },
  {
    tipo: 'TRANSFORMACION' as const,
    cliente: 'Agropecuaria Los Naranjos Ltda',
    cedula: '800987654',
    telefono: '2618765432',
    email: 'losnaranjos@agro.com',
    runt: {
      placa: 'XYZ258', marca: 'JAC Motors', linea: 'T6 Pro', modelo: '2021',
      color: 'Verde Militar', claseVehiculo: 'camioneta', combustible: 'gasolina',
      noMotor: 'HFC4GA258369B',   noChasis: 'LKXTLBA27MB258369',
      noSerie: 'LKXTLBA27MB258369', noVin: 'LKXTLBA27MB258369',
      tipoServicio: 'oficial', carroceriaCodigo: 'P04', carroceriaTipo: 'DOBLE CABINA',
      capacidadKg: '1500', blindaje: false, potenciaHp: '136', cilindrada: '2000',
      propPrimerApellido: 'Naranjos',  propSegundoApellido: 'Ltda',
      propNombres: 'Agropecuaria Los', propTipoDocumento: 'nit',
      propNoDocumento: '800987654-2',  propDireccion: 'Km 5 Vía Chicoral',
      propCiudad: 'Espinal',           propTelefono: '2618765432',
      alertaHurto: false, alertaLimPropiedad: false, alertaEmbargo: false,
      observaciones: 'Transformación de gasolina a GNV + carrocería mixta',
    },
  },
  {
    tipo: 'DUPLICADO_LICENCIA_TRANSITO' as const,
    cliente: 'David Santiago Morales Henao',
    cedula: '1193456789',
    telefono: '3165678901',
    email: 'dmorales@gmail.com',
    runt: {
      placa: 'ABD369', marca: 'Honda', linea: 'CB190R', modelo: '2023',
      color: 'Rojo', claseVehiculo: 'motocicleta', combustible: 'gasolina',
      noMotor: 'CB190E369147B',   noChasis: 'JH2ME07ABN0369147',
      noSerie: 'JH2ME07ABN0369147', noVin: 'JH2ME07ABN0369147',
      tipoServicio: 'particular', carroceriaCodigo: 'M01', carroceriaTipo: 'MOTOCICLETA',
      capacidadKg: '180', blindaje: false, potenciaHp: '16', cilindrada: '184',
      propPrimerApellido: 'Morales',  propSegundoApellido: 'Henao',
      propNombres: 'David Santiago',  propTipoDocumento: 'cc',
      propNoDocumento: '1193456789',  propDireccion: 'Cll 42 # 7-89 Las Delicias',
      propCiudad: 'Ibagué',           propTelefono: '3165678901',
      alertaHurto: false, alertaLimPropiedad: false, alertaEmbargo: false,
      observaciones: 'Licencia extraviada. Se expide duplicado.',
    },
  },
  {
    tipo: 'INSCRIPCION_PRENDA' as const,
    cliente: 'Gloria Inés Suárez Palomino',
    cedula: '38901234',
    telefono: '3101234567',
    email: null,
    runt: {
      placa: 'CEF741', marca: 'Kia', linea: 'Picanto Ion', modelo: '2022',
      color: 'Naranja', claseVehiculo: 'automovil', combustible: 'gasolina',
      noMotor: 'G3LA741852C',    noChasis: 'KNAFB511XN6741852',
      noSerie: 'KNAFB511XN6741852', noVin: 'KNAFB511XN6741852',
      tipoServicio: 'particular', carroceriaCodigo: 'C01', carroceriaTipo: 'HATCHBACK',
      capacidadKg: '375', blindaje: false, potenciaHp: '62', cilindrada: '1000',
      propPrimerApellido: 'Suárez',   propSegundoApellido: 'Palomino',
      propNombres: 'Gloria Inés',     propTipoDocumento: 'cc',
      propNoDocumento: '38901234',    propDireccion: 'Cra 15 # 28-40 Ricaurte',
      propCiudad: 'Ibagué',           propTelefono: '3101234567',
      alertaHurto: false, alertaLimPropiedad: true, alertaEmbargo: false,
      alertaOtro: 'Prenda a favor de Bancolombia — Crédito 7845963',
      observaciones: 'Inscripción de prenda por crédito de vehículo nuevo',
    },
  },
  {
    tipo: 'LEVANTA_PRENDA' as const,
    cliente: 'Rodrigo Emilio Torres Ávila',
    cedula: '79001122',
    telefono: '3132345678',
    email: 'retorres@live.com',
    runt: {
      placa: 'GHI852', marca: 'Hyundai', linea: 'i10 Prime', modelo: '2020',
      color: 'Gris', claseVehiculo: 'automovil', combustible: 'gasolina',
      noMotor: 'G4LATK852963D',  noChasis: 'KMHCT41GP0U852963',
      noSerie: 'KMHCT41GP0U852963', noVin: 'KMHCT41GP0U852963',
      tipoServicio: 'particular', carroceriaCodigo: 'C01', carroceriaTipo: 'HATCHBACK',
      capacidadKg: '400', blindaje: false, potenciaHp: '65', cilindrada: '1086',
      propPrimerApellido: 'Torres',  propSegundoApellido: 'Ávila',
      propNombres: 'Rodrigo Emilio', propTipoDocumento: 'cc',
      propNoDocumento: '79001122',   propDireccion: 'Cl 19 # 4-55 San Simón',
      propCiudad: 'Ibagué',          propTelefono: '3132345678',
      alertaHurto: false, alertaLimPropiedad: false, alertaEmbargo: false,
      observaciones: 'Levanta prenda por cancelación total del crédito vehículo',
    },
  },
  {
    tipo: 'CANCELACION_MATRICULA_REGISTRO' as const,
    cliente: 'Ernesto Fabián Duque Castro',
    cedula: '71890345',
    telefono: '3189012345',
    email: null,
    runt: {
      placa: 'JKL963', marca: 'Mitsubishi', linea: 'L300 Panel', modelo: '2008',
      color: 'Blanco', claseVehiculo: 'camioneta', combustible: 'diesel',
      noMotor: '4D56U963741E',    noChasis: 'JMBYNL3W2BJ963741',
      noSerie: 'JMBYNL3W2BJ963741', noVin: 'JMBYNL3W2BJ963741',
      tipoServicio: 'particular', carroceriaCodigo: 'P03', carroceriaTipo: 'FURGON',
      capacidadKg: '1200', blindaje: false, potenciaHp: '85', cilindrada: '2477',
      propPrimerApellido: 'Duque',  propSegundoApellido: 'Castro',
      propNombres: 'Ernesto Fabián', propTipoDocumento: 'cc',
      propNoDocumento: '71890345',   propDireccion: 'Kra 9 # 18B-20 Calambeo',
      propCiudad: 'Ibagué',          propTelefono: '3189012345',
      alertaHurto: false, alertaLimPropiedad: false, alertaEmbargo: false,
      observaciones: 'Cancelación por chatarrización voluntaria',
    },
  },
  {
    tipo: 'CAMBIO_PLACAS' as const,
    cliente: 'Marcela Andrea Peñuela Lagos',
    cedula: '1030112233',
    telefono: '3156789012',
    email: 'mpenuela@gmail.com',
    runt: {
      placa: 'MNO174', marca: 'Volkswagen', linea: 'Gol Trendline', modelo: '2018',
      color: 'Verde Lima', claseVehiculo: 'automovil', combustible: 'gasolina',
      noMotor: 'CHPB174285F',    noChasis: '9BWZZZ377JT174285',
      noSerie: '9BWZZZ377JT174285', noVin: '9BWZZZ377JT174285',
      tipoServicio: 'particular', carroceriaCodigo: 'C01', carroceriaTipo: 'HATCHBACK',
      capacidadKg: '430', blindaje: false, potenciaHp: '101', cilindrada: '1598',
      propPrimerApellido: 'Peñuela', propSegundoApellido: 'Lagos',
      propNombres: 'Marcela Andrea', propTipoDocumento: 'cc',
      propNoDocumento: '1030112233',  propDireccion: 'Cl 38 # 6A-12 Jardín',
      propCiudad: 'Ibagué',           propTelefono: '3156789012',
      alertaHurto: false, alertaLimPropiedad: false, alertaEmbargo: false,
      observaciones: 'Cambio de placas por deterioro y solicitud voluntaria',
    },
  },
  {
    tipo: 'DUPLICADO_PLACAS' as const,
    cliente: 'Oswaldo Humberto Mena Cárdenas',
    cedula: '19234567',
    telefono: '3190123456',
    email: null,
    runt: {
      placa: 'PQR285', marca: 'Chevrolet', linea: 'N300 Max Work', modelo: '2020',
      color: 'Blanco', claseVehiculo: 'camioneta', combustible: 'gasolina',
      noMotor: 'LMU285396G',    noChasis: 'KL1SBEH28LB285396',
      noSerie: 'KL1SBEH28LB285396', noVin: 'KL1SBEH28LB285396',
      tipoServicio: 'particular', carroceriaCodigo: 'P04', carroceriaTipo: 'PICKUP',
      capacidadKg: '800', blindaje: false, potenciaHp: '82', cilindrada: '1400',
      propPrimerApellido: 'Mena',     propSegundoApellido: 'Cárdenas',
      propNombres: 'Oswaldo Humberto', propTipoDocumento: 'cc',
      propNoDocumento: '19234567',     propDireccion: 'Cll 30 # 3-45 Boquerón',
      propCiudad: 'Ibagué',            propTelefono: '3190123456',
      alertaHurto: false, alertaLimPropiedad: false, alertaEmbargo: false,
      observaciones: 'Placa trasera robada. Denuncio 2024-IB-00789.',
    },
  },
  {
    tipo: 'REMATRICULA' as const,
    cliente: 'Yesenia Carolina Ríos Muñoz',
    cedula: '1070456789',
    telefono: '3209876543',
    email: 'yrios@outlook.com',
    runt: {
      placa: 'STU396', marca: 'Suzuki', linea: 'GS150 NE', modelo: '2021',
      color: 'Azul Cobalto', claseVehiculo: 'motocicleta', combustible: 'gasolina',
      noMotor: 'F8B396507H',     noChasis: 'JS1GE7CA5M0396507',
      noSerie: 'JS1GE7CA5M0396507', noVin: 'JS1GE7CA5M0396507',
      tipoServicio: 'particular', carroceriaCodigo: 'M01', carroceriaTipo: 'MOTOCICLETA',
      capacidadKg: '150', blindaje: false, potenciaHp: '13', cilindrada: '150',
      propPrimerApellido: 'Ríos',    propSegundoApellido: 'Muñoz',
      propNombres: 'Yesenia Carolina', propTipoDocumento: 'cc',
      propNoDocumento: '1070456789',  propDireccion: 'Kra 4B # 55-23 Malabar',
      propCiudad: 'Ibagué',           propTelefono: '3209876543',
      alertaHurto: false, alertaLimPropiedad: false, alertaEmbargo: false,
      observaciones: 'Rematrícula por vencimiento de registro anterior',
    },
  },
  {
    tipo: 'CAMBIO_CARROCERIA' as const,
    cliente: 'Distribuidora El Tolima Grande SAS',
    cedula: '901234567',
    telefono: '2619876543',
    email: 'flotavehiculos@tolimag.com',
    runt: {
      placa: 'VWX417', marca: 'Hino', linea: '300 XZU620', modelo: '2017',
      color: 'Amarillo', claseVehiculo: 'camion', combustible: 'diesel',
      noMotor: 'N04CT417528I',   noChasis: 'JHFJTU62ZHX417528',
      noSerie: 'JHFJTU62ZHX417528', noVin: 'JHFJTU62ZHX417528',
      tipoServicio: 'publico', carroceriaCodigo: 'T02', carroceriaTipo: 'FURGON REFRIGERADO',
      capacidadKg: '6000', blindaje: false, potenciaHp: '150', cilindrada: '4009',
      propPrimerApellido: 'Grande',   propSegundoApellido: 'SAS',
      propNombres: 'Distribuidora El Tolima', propTipoDocumento: 'nit',
      propNoDocumento: '901234567-8', propDireccion: 'Zona Industrial Cll 60 # 2-30',
      propCiudad: 'Ibagué',           propTelefono: '2619876543',
      alertaHurto: false, alertaLimPropiedad: false, alertaEmbargo: false,
      observaciones: 'Cambio de carrocería furgón seco a furgón refrigerado',
    },
  },
  {
    tipo: 'OTROS' as const,
    cliente: 'Felipe Augusto Gómez Leal',
    cedula: '1115678901',
    telefono: '3174321098',
    email: 'fgomez@gmail.com',
    runt: {
      placa: 'YZA528', marca: 'Bajaj', linea: 'Boxer BM150X', modelo: '2022',
      color: 'Negro', claseVehiculo: 'motocicleta', combustible: 'gasolina',
      noMotor: 'DHZBEF528639J',  noChasis: 'MD2BXES22SC528639',
      noSerie: 'MD2BXES22SC528639', noVin: 'MD2BXES22SC528639',
      tipoServicio: 'particular', carroceriaCodigo: 'M01', carroceriaTipo: 'MOTOCICLETA',
      capacidadKg: '150', blindaje: false, potenciaHp: '14', cilindrada: '150',
      propPrimerApellido: 'Gómez',   propSegundoApellido: 'Leal',
      propNombres: 'Felipe Augusto', propTipoDocumento: 'cc',
      propNoDocumento: '1115678901', propDireccion: 'Cll 10 # 9-12 Cooperativa',
      propCiudad: 'Ibagué',          propTelefono: '3174321098',
      alertaHurto: false, alertaLimPropiedad: false, alertaEmbargo: false,
      observaciones: 'Corrección de datos — error en nombre del propietario anterior',
    },
  },
  {
    tipo: 'MATRICULA_REGISTRO' as const,
    cliente: 'Camilo Andrés Bedoya Ríos',
    cedula: '1094567823',
    telefono: '3118765432',
    email: 'cbedoya@gmail.com',
    runt: {
      placa: 'BRD10B',
      marca: 'Yamaha',
      linea: 'FZ25',
      modelo: '2023',
      color: 'Negro',
      claseVehiculo: 'motocicleta',
      combustible: 'gasolina',
      noMotor: 'E3N1E10B001234',
      noChasis: 'ME1RE251XP0010B12',
      noSerie: 'ME1RE251XP0010B12',
      noVin: 'ME1RE251XP0010B12',
      tipoServicio: 'particular',
      carroceriaCodigo: 'M01',
      carroceriaTipo: 'MOTOCICLETA',
      capacidadKg: '180',
      blindaje: false,
      potenciaHp: '21',
      cilindrada: '249',
      propPrimerApellido: 'Bedoya',
      propSegundoApellido: 'Ríos',
      propNombres: 'Camilo Andrés',
      propTipoDocumento: 'cc',
      propNoDocumento: '1094567823',
      propDireccion: 'Cll 52 # 4A-18 El Salado',
      propCiudad: 'Ibagué',
      propTelefono: '3118765432',
      alertaHurto: false,
      alertaLimPropiedad: false,
      alertaEmbargo: false,
      observaciones: 'Matrícula inicial moto nueva de concesionario Yamaha',
    },
  },
  {
    tipo: 'TRASPASO' as const,
    cliente: 'Natalia Paola Díaz Herrera',
    cedula: '1007890123',
    telefono: '3145678901',
    email: 'ndiaz@hotmail.com',
    runt: {
      placa: 'KLM20C',
      marca: 'Honda',
      linea: 'XRE300',
      modelo: '2022',
      color: 'Rojo/Negro',
      claseVehiculo: 'motocicleta',
      combustible: 'gasolina',
      noMotor: 'NC43E20C005678',
      noChasis: 'JH2ND0430NM20C56',
      noSerie: 'JH2ND0430NM20C56',
      noVin: 'JH2ND0430NM20C56',
      tipoServicio: 'particular',
      carroceriaCodigo: 'M01',
      carroceriaTipo: 'MOTOCICLETA',
      capacidadKg: '180',
      blindaje: false,
      potenciaHp: '25',
      cilindrada: '286',
      propPrimerApellido: 'Romero',
      propSegundoApellido: 'Cárdenas',
      propNombres: 'Luis Miguel',
      propTipoDocumento: 'cc',
      propNoDocumento: '79345612',
      propDireccion: 'Kra 8 # 30-14 Ambala',
      propCiudad: 'Ibagué',
      propTelefono: '3123456780',
      compPrimerApellido: 'Díaz',
      compSegundoApellido: 'Herrera',
      compNombres: 'Natalia Paola',
      compTipoDocumento: 'cc',
      compNoDocumento: '1007890123',
      compDireccion: 'Cll 37 # 5-22 San Simón',
      compCiudad: 'Ibagué',
      compTelefono: '3145678901',
      alertaHurto: false,
      alertaLimPropiedad: false,
      alertaEmbargo: false,
      observaciones: 'Traspaso moto usada entre particulares — venta directa',
    },
  },
  {
    tipo: 'CAMBIO_PLACAS' as const,
    cliente: 'Jorge Iván Salazar Mendoza',
    cedula: '71234890',
    telefono: '3162345678',
    email: null,
    runt: {
      placa: 'ZAP15D',
      marca: 'Bajaj',
      linea: 'Pulsar NS200',
      modelo: '2021',
      color: 'Azul',
      claseVehiculo: 'motocicleta',
      combustible: 'gasolina',
      noMotor: 'DHZBBF15D009321',
      noChasis: 'MD2B5AZ22MC15D93',
      noSerie: 'MD2B5AZ22MC15D93',
      noVin: 'MD2B5AZ22MC15D93',
      tipoServicio: 'particular',
      carroceriaCodigo: 'M01',
      carroceriaTipo: 'MOTOCICLETA',
      capacidadKg: '180',
      blindaje: false,
      potenciaHp: '24',
      cilindrada: '199',
      propPrimerApellido: 'Salazar',
      propSegundoApellido: 'Mendoza',
      propNombres: 'Jorge Iván',
      propTipoDocumento: 'cc',
      propNoDocumento: '71234890',
      propDireccion: 'Cra 2 # 17-55 Boquerón',
      propCiudad: 'Ibagué',
      propTelefono: '3162345678',
      alertaHurto: false,
      alertaLimPropiedad: false,
      alertaEmbargo: false,
      observaciones: 'Cambio de placas moto — placa delantera dañada por accidente',
    },
  },
] as const

export default class TramitesPruebaSeeder extends BaseSeeder {
  public async run() {
    const trx = await db.transaction()
    try {
      // ── Obtener usuario y servicio de referencia ──────────────────────
      const usuario = await Usuario.query({ client: trx }).where('sede_id', SEDE_ID).first()
      if (!usuario) {
        console.warn('[TramitesPruebaSeeder] No hay usuarios en sede_id=1. Abortando.')
        await trx.commit()
        return
      }

      const servicio = await Servicio.query({ client: trx })
        .whereILike('codigo_servicio', 'TRAMITES')
        .first()
      if (!servicio) {
        console.warn('[TramitesPruebaSeeder] Servicio TRAMITES no encontrado. Abortando.')
        await trx.commit()
        return
      }

      // ── Número de turno inicial (consecutivo desde el máximo del día) ─
      const rowMax = await trx
        .from('tramites')
        .where('sede_id', SEDE_ID)
        .where('fecha', HOY.toISODate()!)
        .max('turno_numero as max')
        .first()
      let turnoBase = Number(rowMax?.max ?? 0)

      // ── Crear 18 trámites + formularios_runt ─────────────────────────
      for (let i = 0; i < DATOS.length; i++) {
        const d = DATOS[i]
        turnoBase++

        const rand = Math.random().toString(36).slice(2, 6).toUpperCase()
        const nowFmt = DateTime.local().setZone('America/Bogota').toFormat('yyyyMMddHHmmssSSS')
        const turnoCodigo = `TRM-${nowFmt}-${rand}-${String(i + 1).padStart(2, '0')}`

        const tramite = await Tramite.create(
          {
            sedeId:       SEDE_ID,
            funcionarioId: usuario.id,
            servicioId:   servicio.id,
            nombreCliente: d.cliente,
            cedula:        d.cedula,
            telefono:      d.telefono ?? null,
            email:         d.email ?? null,
            turnoNumero:   turnoBase,
            turnoCodigo,
            tipoTramite:   d.tipo,
            estado:        'completado',
            fecha:         HOY,
            horaIngreso:   `${String(8 + i).padStart(2, '0')}:00`,
            horaAtencion:  `${String(8 + i).padStart(2, '0')}:05`,
            horaFin:       `${String(8 + i).padStart(2, '0')}:${String(20 + i).padStart(2, '0')}`,
            tiempoAtencion: `${15 + i} min`,
            observaciones:  d.runt.observaciones,
            resultado:     'Trámite completado satisfactoriamente',
          } as any,
          { client: trx }
        )

        const r = d.runt as any
        await FormularioRunt.create(
          {
            tramiteId:    tramite.id,
            placa:        r.placa,
            marca:        r.marca,
            linea:        r.linea,
            modelo:       r.modelo,
            color:        r.color,
            claseVehiculo: r.claseVehiculo,
            combustible:  r.combustible,
            noMotor:      r.noMotor,
            noChasis:     r.noChasis,
            noSerie:      r.noSerie,
            noVin:        r.noVin,
            tipoServicio: r.tipoServicio,
            carroceriaCodigo: r.carroceriaCodigo,
            carroceriaTipo:   r.carroceriaTipo,
            capacidadKg:  r.capacidadKg,
            blindaje:     r.blindaje,
            potenciaHp:   r.potenciaHp,
            cilindrada:   r.cilindrada,
            // Propietario
            propPrimerApellido:  r.propPrimerApellido,
            propSegundoApellido: r.propSegundoApellido,
            propNombres:         r.propNombres,
            propTipoDocumento:   r.propTipoDocumento,
            propNoDocumento:     r.propNoDocumento,
            propDireccion:       r.propDireccion,
            propCiudad:          r.propCiudad,
            propTelefono:        r.propTelefono,
            // Comprador (solo TRASPASO)
            compPrimerApellido:  r.compPrimerApellido  ?? null,
            compSegundoApellido: r.compSegundoApellido ?? null,
            compNombres:         r.compNombres         ?? null,
            compTipoDocumento:   r.compTipoDocumento   ?? null,
            compNoDocumento:     r.compNoDocumento      ?? null,
            compDireccion:       r.compDireccion       ?? null,
            compCiudad:          r.compCiudad          ?? null,
            compTelefono:        r.compTelefono        ?? null,
            // Importación
            importacionTipo:         r.importacionTipo         ?? null,
            importacionNoDocumento:  r.importacionNoDocumento  ?? null,
            importacionFecha: r.importacionFecha
              ? DateTime.fromISO(r.importacionFecha, { zone: 'America/Bogota' })
              : null,
            // Alertas
            alertaHurto:         r.alertaHurto,
            alertaLimPropiedad:  r.alertaLimPropiedad,
            alertaEmbargo:       r.alertaEmbargo,
            alertaOtro:          r.alertaOtro ?? null,
            observaciones:       r.observaciones,
          } as any,
          { client: trx }
        )

        console.log(`  [${i + 1}/21] ${d.tipo} — ${d.runt.placa} — turno #${turnoBase}`)
      }

      await trx.commit()
      console.log('[TramitesPruebaSeeder] 21 trámites + formularios RUNT creados correctamente.')
    } catch (error) {
      await trx.rollback()
      throw error
    }
  }
}
